### ISSUE TITLE
Criar uma imagem Linux AMI customizada na AWS

### ISSUE THREAD

**Issue by Mateusmsouza** [antena-dream-team/AntenasService#10]
Atualmente quando criamos uma máquina na EC2 AWS, antes de subir o serviço nela precisa-se fazer várias configurações:
- Instalar git, docker e docker-compose;
- clonar o repositório AntenasService.

Para melhorar este cenário, o time do Antenas precisa de uma imagem customizada na AWS, feita a partir da Linux AMI (a opção que é inclusiva no free tier), as configurações necessárias citadas acima, e com o repositório AntenasService clonado na pasta do usuário.

**Comment by ThiagoDisk** [comment]
If needed, how to reproduce the scenario and install git, clone repo, install docker and docker-compose.
########################################################
Shell
#Create an EC2 instance with Amazon Linux 2 with internet access
#Connect to your instance using putty
user :  ec2-user

#Perform a quick update on your instance:
sudo yum update -y

#Install git in your EC2 instance
sudo yum install git -y

#Check git version
git version
##########################################################
To get Docker running on the AWS AMI you should follow the steps below (these are all assuming you have ssh'd on to the EC2 instance).

#Update the packages on your instance
sudo yum update -y

#Install Docker
sudo yum install docker -y

#Start the Docker Service
sudo service docker start

#Add the ec2-user to the docker group so you can execute Docker commands without using sudo.

sudo usermod -a -G docker ec2-user

#You should then be able to run all of the docker commands without requiring sudo. 
##########################################################
#If you need to clone a repo from git that only accepts SSH
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
ssh-add ~/.ssh/id_rsa
##########################################################
#Install docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

#To install a different version of Compose, substitute 1.26.0 with the version of Compose you want to use.

#Apply executable permissions to the binary:
sudo chmod +x /usr/local/bin/docker-compose

#Test
 docker-compose --version
